### ISSUE TITLE
ModuleNotFoundError with css external assets. How to handle css assets?

### ISSUE THREAD

**Issue by equinusocio** [aruntk/wc-loader#27] opened 2017-08-09 15:13 UTC
Hi, i have this css snippet inside my web component:

```css
:host {
  display: flex;
  contain: content;
  position: relative;
  overflow: hidden;
  background-image: url("/assets/images/thread-row-placeholder.svg");
}
```

I get this error:
```
Module not found: Error: Can't resolve '/assets/images/thread-row-placeholder.svg'
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve '/assets/images/thread-row-placeholder.svg'
```

How do you suppose to handle external assets in css?

Atm i have to comment out this portion of the lib to get things work.
```js
var processed = text.replace(/url\(["']?((?!.*:\/\/|"|'|\)).+?)["']?\)/ig, function (_u, url) {
    // to get -> filepath from url(filepath), url('filepath') and url('filepath')
    return 'url(' + self._changeRelUrl(url, _path2.default.dirname(cssBasePath)) + ')';
});
return processed;
```

I'm on `webpack 3.4.1` and `wc-loader 1.1.9`

**Comment by aruntk** [comment] 2017-08-09 18:04
@equinusocio try using `assets/` instead of `/assets/`. Latter one refers to assets folder inside your root folder. As the error suggests webpack could not resolve the absolute path `/assets/images/thread-row-placeholder.svg`. 

Or use absolute path to svg file. `/path/to/assets/`. 

```css
:host {
  display: flex;
  contain: content;
  position: relative;
  overflow: hidden;
  background-image: url("assets/images/thread-row-placeholder.svg");
}
```

Refer the example here https://github.com/aruntk/polymer-webpack-demo/blob/master/src/components/example-app.html#L25

Dont forget to define image loaders in your webpack config. eg https://github.com/aruntk/polymer-webpack-demo/blob/master/webpack.config.js#L22-L28

**Comment by equinusocio** [comment] 2017-08-09 18:57
I'm already using file-loader and i get this error anyway. My assets folder live inside the root. 

Does the wc-loader follow the css url's starting from the css file?

**Comment by aruntk** [comment] 2017-08-09 20:15
@equinusocio Reopening the issue. I've identified the cause. Working on it.

**Comment by aruntk** [comment] 2017-08-09 21:20
Fixed in commit https://github.com/aruntk/wc-loader/commit/9bb2b836718ec9d386b0ebe7651731fe1ee975b4. 

Solution

1. Update to v1.1.10

2. Change webpack config according to https://github.com/aruntk/wc-loader#root-relative-urls

## Update
I've released 1.1.11 with dependencies updated. So you might want to try that one instead of 1.1.10

**Closed as completed by aruntk** 2017-08-09 21:20 UTC

**Comment by equinusocio** [comment] 2017-08-10 07:15
@aruntk I tried `1.1.12` (with file-loader) and i get the same error:

with `root=/` and css url `/assets/images/thread-row-placeholder.svg`
it search for — **//assets/images/thread-row-placeholder.svg** — and return the Module not found error

---

with `root=/` and css url `assets/images/thread-row-placeholder.svg`
it search for — **./assets/images/thread-row-placeholder.svg** — and return the Module not found error


**I'm missing something?**

---

### EDIT
It works if i set `root=/` and the css url to `../../../assets/images/thread-row-placeholder.svg`. 

### EDIT 2
I solved by removing `root=/` and set `useRelativePath: false` to file-loader. This is the only way found to get it works. @aruntk Maybe you should write a bit of documentation.

**Comment by aruntk** [comment] 2017-08-10 08:37
@equinusocio absolute path is working in 1.1.12. See the following screenshots. 

<img width="636" alt="screen shot 2017-08-10 at 1 31 49 pm" src="https://user-images.githubusercontent.com/6007432/29160609-8ce8a31e-7dd0-11e7-93bc-a45fc3082614.png">

<img width="452" alt="screen shot 2017-08-10 at 1 32 36 pm" src="https://user-images.githubusercontent.com/6007432/29160627-9f8ec444-7dd0-11e7-8548-a59b0b88aebf.png">

see the background image.
<img width="1280" alt="screen shot 2017-08-10 at 1 32 49 pm" src="https://user-images.githubusercontent.com/6007432/29161760-10472ed4-7dd5-11e7-99e6-4c68a58b09e5.png">

Could you check the access permissions of assets folder?

**Comment by aruntk** [comment] 2017-08-10 09:24
@equinusocio It seems to be working fine in my system even without setting `useRelativePath: false`.

This is my webpack config https://github.com/aruntk/polymer-webpack-demo/blob/master/webpack.config.js#L43

I'll try to add better documentation. Thanks for the suggestion :)
